// Generated by CoffeeScript 1.7.1
(function() {
  var showEditor;

  showEditor = function() {
    var backEl, codeEl, link, preEl, script;
    document.body.className += ' debug';
    preEl = document.createElement("pre");
    codeEl = document.createElement("code");
    preEl.appendChild(codeEl);
    document.body.appendChild(preEl);
    backEl = document.createElement("a");
    backEl.href = "/";
    backEl.className = "back";
    document.body.appendChild(backEl);
    link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = "macClassicTheme.css";
    document.head.appendChild(link);
    script = document.createElement("script");
    script.src = "//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js";
    document.head.appendChild(script);
    return script.onload = function() {
      var code;
      code = document.querySelector("#script").textContent.trim();
      code = hljs.highlight("javascript", code).value;
      return codeEl.innerHTML = code;
    };
  };

  if (window === window.top) {
    showEditor();
  }

}).call(this);
